Vagrant::Config.run do |config|
  config.vm.box = "squeeze64"
  config.vm.box_url = "http://download.virtualbox.org/virtualbox/4.2.0/virtualbox-4.2_4.2.0-80737~Debian~squeeze_amd64.deb"
  config.vm.network :hostonly, "123.123.123.123"
  config.vm.share_folder "v-cookbooks", "/cookbooks", "."
end
