#!/usr/bin/perl 

#------------------------------------------------------------------------------
#
# Copyright  (c) SWM  2003
#
#------------------------------------------------------------------------------
#
# Modification History
#
# Auth    Date       Description
# ------  ---------  ----------------------------------------------------------
# SWM     10 Apr 03  Took away print from $t->process, now writes to a file
#                      so no need to pipe at the command line and put in a
#                      system call to edit the file.  
# SWM     28 Feb 03  Changed the INCLUDE_PATH to be stub_templates instead
#                      of swmcc.
# SWM     04 Feb 03  Wrote this
#------------------------------------------------------------------------------

=head1 NAME

build_test - builds the stubs on top all the test scripts I write. 

=head1 SYNOPSIS

 /usr/local/bin/build_test

=head1 DESCRIPTION

This creates all the stubs for my test scripts. 

=head1 BUGS

None Known.

=head1 TODO

=over 4

=item * make the copyright an option.

=back

=cut

#------------------------------------------------------------------------------
use strict;
use warnings;
use Getopt::Long;
use Template;
use Date::Simple;

my $usage = qq{
  [build_test]  

  --namespace - the namespace of the module you are testing
  --package   = the name of the package you are testing

  i.e. build_test --namespace=SWM --package=Session
  
};

my $namespace; 
my $package;   
GetOptions ('namespace=s' => \$namespace, 'package=s' => \$package);

die $usage . 'need a namespace' unless ( defined $namespace ); 
die $usage . 'need a package'   unless ( defined $package   ); 

my $vars = {
        module     => $package,
        namespace  => $namespace,
        date       => Date::Simple->new, 
};


my $t = Template->new(
      INCLUDE_PATH => '/var/templates/scripts/stub_templates/',
);

$t->process('testscript', $vars, "$package.t");
system("vim $package.t");
